/// Harf adı / harf şekli ile ses dosyası kökü eşlemesi.
/// Flutter'a bağlı değildir; ses üretim araçları da bu tabloyu okur.
library;

const elifbaAudioNames = <String, String>{
  'elif': 'elif',
  'be': 'ba',
  'te': 'ta',
  'se': 'tha',
  'cim': 'jim',
  'ha': 'ha',
  'hı': 'kha',
  'hi': 'kha',
  'dal': 'dal',
  'zel': 'dhal',
  'ra': 'ra',
  'ze': 'zay',
  'sin': 'sin',
  'şın': 'shin',
  'sad': 'sad',
  'dad': 'dad',
  'tı': 'ta_heavy',
  'zı': 'za_heavy',
  'ayn': 'ayn',
  'gayın': 'ghayn',
  'gayn': 'ghayn',
  'fe': 'fa',
  'kaf': 'qaf',
  'kef': 'kaf',
  'lam': 'lam',
  'mim': 'mim',
  'nun': 'nun',
  'he': 'hah',
  'vav': 'waw',
  'ye': 'ya',
  'ya': 'ya',
};

const elifbaAudioGlyphs = <String, String>{
  'ا': 'elif',
  'أ': 'elif',
  'إ': 'elif',
  'ب': 'ba',
  'ت': 'ta',
  'ث': 'tha',
  'ج': 'jim',
  'ح': 'ha',
  'خ': 'kha',
  'د': 'dal',
  'ذ': 'dhal',
  'ر': 'ra',
  'ز': 'zay',
  'س': 'sin',
  'ش': 'shin',
  'ص': 'sad',
  'ض': 'dad',
  'ط': 'ta_heavy',
  'ظ': 'za_heavy',
  'ع': 'ayn',
  'غ': 'ghayn',
  'ف': 'fa',
  'ق': 'qaf',
  'ك': 'kaf',
  'ل': 'lam',
  'م': 'mim',
  'ن': 'nun',
  'ه': 'hah',
  'و': 'waw',
  'ي': 'ya',
  'ى': 'ya',
};
